name: Deploy to GH pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Trunk
      run: cargo install trunk
    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: trunk build
    - name: Add .nojekyll file
      run: touch dist/.nojekyll
    - name: Run tests
      run: cargo test --verbose
    - name: Commit dist to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
