name: Deploy to GH pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  id-token: write
  pages: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        target: wasm32-unknown-unknown
    - name: Install trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: latest
    - name: Install WASM Binary Toolkit
      run: sudo apt-get install -y binaryen
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: trunk build --release
    - name: Optimize WASM
      run: find dist -name "*.wasm" -exec wasm-opt {} -o {} -Oz -c --dae --dce --rse -s 4 --vacuum \;
    - name: Add .nojekyll file
      run: touch dist/.nojekyll
    - name: Run tests
      run: cargo test --verbose
    - name: Prepare GitHub Pages
      uses: actions/configure-pages@v3
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v2
    - name: Deploy Pages
      uses: actions/deploy-pages@v2
