name: Deploy to GH pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

#permissions:
#  id-token: write
#  pages: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        target: wasm32-unknown-unknown
    - name: Install trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: latest
    - name: Install WASM Binary Toolkit
      run: sudo apt-get install -y binaryen
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: trunk build --release --public-url /wasm_mini_demo_rust/
    - name: Optimize WASM
      run: find dist -name "*.wasm" -exec wasm-opt {} -o {} -Oz -c --dae --dce --rse -s 4 --vacuum \;
    #- name: Patch base href
    #  uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
    #  with:
    #      html_path: 'dist/index.html'
    #      base_href: '/wasm_mini_demo_rust/'
    - name: Add .nojekyll file
      run: touch dist/.nojekyll
    - name: Run tests
      run: cargo test --verbose
    - name: Commit dist to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
